### PR TITLE
Allow input to resize smaller than the placeholder

### PR DESCRIPTION
**Pull request by TobyAbel**
When using a long placeholder, this allows the input to shrink down to match the text size when the text is smaller than the input.

I don't know if that's desired behaviour for the general use case, but it made sense for us. If most other people find the same, it could be a useful PR, otherwise it's here for anyone who wants it.

### CODE REVIEW

**Comment by TobyAbel** [comment]
(please excuse the unnecessary newline addition - I think that's Github's online edit being a little overzealous, rather than me expressing religion ;) )

**Comment by JedWatson** [comment]
I think this would be a useful addition if it could be controlled with a prop, as the current behaviour is important for other use-cases (e.g. where the input is used in a wrapping list of tags; you don't want it jumping up to the previous line when you start typing if the placeholder is enough to cause a wrap but a few characters isn't)

I'm not sure what a clear name for such a prop would be... maybe `shrinkToValue`?

**Comment by JedWatson** [comment]
@TobyAbel do you want to update this PR to use the prop or should we close it? I'm happy to add this, just let me know if you're still interested.

**Comment by ahstro** [comment]
This would be wonderful! Couldn't you pull it and merge via command line, @JedWatson ? I could create my own PR, but I don't want to steal credit from @TobyAbel.

**Comment by ahstro** [comment]
I went ahead and fixed this, the prop thing and updated the example on my branch. I see now that @TobyAbel seems to be doing something, so this might've been unnecessary, feel free to pull my commit if it comes to that. :smile:

**Comment by TobyAbel** [comment]
@ahstro woops, looks like I chose the worst possible time to get around to this ;)
@JedWatson sorry to be re-joining the conversation so late. The PR's a bit uglier now since I went ahead and rebuilt / added an example, but the propType's in if you'd like to accept it

**Comment by ahstro** [comment]
@JedWatson bump :innocent:

**Comment by ansonkao** [comment]
Totally missed this PR and made a duplicate @ #46 haha. Bump, @JedWatson!

**Comment by JedWatson** [comment]
Merged #46, thanks guys :)

**Pull request closed without merging**
