### PR TITLE
Migrate to React 15.5

### PR DESCRIPTION
**Pull request by nodtem66**
Accoding to [React 15.5](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) updates
this patch remove deprecation warnings with following details:
- use createClass from `create-react-class`
- use PropTypes from `prop-types`
- remove `this.isMounted()`

### CODE REVIEW

**Comment by uryyyyyyy** [comment]
👍

**Comment by MichaelDeBoey** [comment]
@JedWatson I think this can be merged?

**Comment by detj** [comment]
Can't wait to see this merged!

**Comment by MichaelDeBoey** [comment]
Closed by #79 (only `isMounted` is still there...)

**Comment by nodtem66** [comment]
Thanks @detj  @MichaelDeBoey and every1 :D

FYI, Difference from #79 

- `lib/AutosizeInput.js` is patched
- remove `isMounted` **(NEED REVIEWED)**

***Reason to remove `isMounted`:***
after patched both `src/AutosizeInput.js` and `lib/AutosizeInput.js` and ran `gulp dev`, resulted in
image

That all

**Pull request closed without merging**
