### PR TITLE
[RFR] fix invalid calling object error

### PR DESCRIPTION
**Pull request by ThieryMichel**
see #29

### CODE REVIEW

**Comment by JedWatson** [comment]
Thanks @ThieryMichel!

**Comment by martin-jujou-sirca** [comment]
@JedWatson any idea when the next release is that includes this commit? IE is unusable without this change

**Comment by cloudkite** [comment]
New npm version would be much appreciated! :pray:

**Comment by JedWatson** [comment]
Done! Sorry for the delay.

**Pull request merged**
