### PR TITLE
moving packages to dependencies [fixes #82]

### LINKED ISSUE #82: Breaking changes in new PATCH version `1.1.3`
Could you please release new major version or move `prop-types` from `devDependencies` to `dependencies` or `peerDependencies`?

Because we have an error:
`Error: Cannot find module 'prop-types'`

### PR DESCRIPTION
**Pull request by palashkaria**
– moving prop-types and create-react-class

### CODE REVIEW

**Comment by mAiNiNfEcTiOn** [comment]
I actually disagree with that.

Adding to `peerDependencies` implies that the current version of it will now imply that devs need to install a dependency before provided by the package.

I'd release a major version moving to peerDependencies and a minor version of this one adding the packages to dependencies :/

**Comment by szarouski** [comment]
I agree with @mAiNiNfEcTiOn

**Comment by asazernik** [comment]
Why not plain old `dependencies`? It is required directly in react-input-autosize code.

**Comment by andreypopp** [comment]
Can this be merged? We have a failing builds and have to specify `create-react-class` and `prop-types` as our app's dependencies even if we don't use them...

**Comment by szarouski** [comment]
Yes, please merge this PR & publish new version, our builds are also failing. Thank you.

**Comment by JedWatson** [comment]
Done - sorry about that, I wish I'd reviewed the PR adding those packages more closely, before I was offline for a couple of weeks 😞 

I believe these should be normal `dependencies`, not keen on adding to `peerDependencies` as multiple versions could reasonably be used in the dependencies of a project, whereas `react` is a special case / exception when it comes to that. This is the most robust solution.

Releasing now.

**Pull request merged**
