### PR TITLE
Warning: componentWillReceiveProps has been renamed

### PR DESCRIPTION
**Pull request by ranneyd**
https://github.com/JedWatson/react-select/issues/3715
https://github.com/JedWatson/react-select/pull/3487
https://github.com/JedWatson/react-select/issues/3720
https://github.com/JedWatson/react-input-autosize/pull/164
https://github.com/JedWatson/react-input-autosize/issues/163
https://github.com/JedWatson/react-select/issues/3773
https://github.com/JedWatson/react-select/issues/3770

### CODE REVIEW

**Comment by graue** [comment]
This will make the lib incompatible with React 15.0 - 16.2. Better to just rename to UNSAFE_componentWillReceiveProps for now.

**Comment by ranneyd** [comment]
@graue what are we going to do when React 17 comes out?

**Comment by ranneyd** [comment]
https://github.com/JedWatson/react-input-autosize/pull/167

**Comment by TriStarGod** [comment]
Sorry, noob question. Why does it matter that replacing depreciated lifecycle methods make it incompatible with React 15.0 - 16.2 if older versions of this component are still available? Thanks!

**Comment by graue** [comment]
Because the incompatibility with React 15.0 - 16.2 would be a breaking change, [semantic versioning](https://docs.npmjs.com/about-semantic-versioning) would require incrementing the major version of this package.

Libraries that depend on this one, like react-select, would then not get the upgrade by default, and would have to also bump their major versions if they manually took the upgrade.

It's preferable to let everyone get the immediate benefit of the console spam going away without having to go through all that.

**Comment by TriStarGod** [comment]
So these types of breaking changes should only be performed when the major version is increased? Then the question becomes why wasn't there a major version change due to react's change. Seems like a tricky balance in keeping up to date with the latest changes and compatibility with other modules. Thanks for your input!

**Comment by jay-khatri** [comment]
I'm getting this error and I'm assuming its relevant to this thread.
```
index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: AutosizeInput
```

What type of work would require a compatible change?

**Pull request closed without merging**
