### PR TITLE
Do not expect window to be defined on init

### PR DESCRIPTION
**Pull request by d4goxn**
Referring to members of the window object on init breaks any apps that uses server side rendering, even if AutosizeInput is not rendered on the server. Since the nextFrame function is not used during a server side render, we can just leave it undefined when there is no window.

### CODE REVIEW

**Comment by Webkadabra** [comment]
Please include this into next release ASAP, @JedWatson

**Comment by snackycracky** [comment]
pelase merge asap @JedWatson

**Comment by snackycracky** [comment]
this is breaking the build of isomorphic applications. The window object is not available.

**Comment by JedWatson** [comment]
Done, sorry for the delay guys and thanks for the fix @d4goxn

**Comment by snackycracky** [comment]
:+1:

**Comment by snackycracky** [comment]
please update react-select to use 0.6.5 as well.

**Comment by JedWatson** [comment]
@snackycracky :+1:

**Pull request merged**
