### PR TITLE
Fix copyInputStyles() never running.

### PR DESCRIPTION
**Pull request by miracle2k**
This was broken in 5da2322b840218781fa42d070efbef2473c8c246.

### CODE REVIEW

**Comment by echenley** [comment]
Thanks for the PR. We're locked to 1.1.0 until this is fixed. Might be worth adding a test for this since it's apparently not covered.

**Comment by jianliangzhao** [comment]
I found this PR after filing a bug for the same issue: https://github.com/JedWatson/react-input-autosize/issues/92

**Comment by dlindenkreuz** [comment]
@JedWatson any updates on this? The above solution seems like an easy fix.

**Comment by miracle2k** [comment]
Until @JedWatson finds the time to merge, I published a built version with this fix, and also including #88 und #85 as `@elsdoerfer/react-input-autosize`

**Comment by JedWatson** [comment]
Thanks @miracle2k, going to publish this now

**Pull request merged**
