### PR TITLE
Adding unit tests

### PR DESCRIPTION
**Pull request by cameronbourke**
## General Questions
1. Should placeholderIsMinWidth have a propTye of bool instead of string,
2. How to structure the tests "describe"?
3. How to move away (if possible) from a dependency on Enzyme's "Full Rendering" and use "Shallow Rendering" instead?
4. How to move away (if possible) from having to run the tests with a browser (currently Chrome)?
5. Currently, the assertions for the width are against the input itself and not the container. Is that correct?
6. Can the core logic that computates the next width be abstracted into a function that can be easily tested. E.g. below

```
...
const currentWidth = getCurrentWidth();
const nextWidth = getNextWidth('example');
expect(currentWidth).toBeLessThan(nextWidth);
```

### CODE REVIEW

**Comment by cameronbourke** [comment]
Currently test #9 is failing due to unexpected behaviour with an `input` if you pass both a `value` and a `defaultValue`.

**Comment by mxstbr** [comment]
1. That makes a lot of sense, no idea why Jed set it to be a String. Jed?
2. What about `"rendering"`, `"adding a placeholder"`, `"changing values"`?
3. a) I think full rendering is fine in this case as there are no child components, so there's no difference, b) simply replacing enzyme's `mount` with `shallow` should pretty much work
4. If doing b) from above, we can then remove `browser-run`
5. Yes, take a look at [line 97](https://github.com/JedWatson/react-input-autosize/blob/c4685c2c4ad54057d5b1dbb4b2677642bb541169/src/AutosizeInput.js#L97), we set the width onto the input so I recon checking it there makes sense. Maybe it'd make sense to also check the width of the container to make sure it resizes accordingly?
6. Not necessary imo, checking [these four cases](https://github.com/JedWatson/react-input-autosize/blob/c4685c2c4ad54057d5b1dbb4b2677642bb541169/src/AutosizeInput.js#L66-L78) from the DOM should be fine. There's too much specific React stuff in there to abstract it away, and we won't reuse it anyway.

Why do we not use [`babel-tape-runner`](https://www.npmjs.com/package/babel-tape-runner), instead compiling with browserify?

**Comment by cameronbourke** [comment]
1. Okay cool, we need @JedWatson to confirm
2. So by that, do you think that the length of the "describes" currently are too long winded?
3. Initially I tried `shallow` rendering, although that wouldn't work because in order for the component to calculate its size it relies on getting the `ref` and `scrollWidth` of the DOM elements.
4. Would love to but cannot because of `3`.
5. Yeah that makes sense, there is the possibility that the input changed its width but the containing div doesn't.

We need to use `browserify ` to create a bundled `js` file that includes the tests which is then run in the the browser.

**Comment by mxstbr** [comment]
2. No, add sub-classes of `describes` :grin:

**Comment by JedWatson** [comment]
👋 hey @cameronbourke 

this is super old, so I'm going to close it - if you feel like expanding test support here still let me know 😄

**Pull request closed without merging**
